config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root :to => 'home#index'
  
  get 'tasks/today', as: 'today'
  get 'tasks/completed_tasks', as: 'completed_tasks'
  resources :categories
  resources :tasks do
    patch :complete
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  
  validates :name, presence: true
  validates :name, length: { in: 1..50 }
  validates :description, length: { maximum: 200 }
  validates_uniqueness_of :name, scope: :user_id
  
  belongs_to :user
  has_many :tasks, :dependent => :destroy

end

app/models/task.rb
class Task < ApplicationRecord

  validates :name, :due_date, presence:true
  validates :name, length: { in: 1..40 }
  validates :description, length: { maximum: 200 }

  belongs_to :category
  belongs_to :user
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
  has_many :tasks

  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

  def after_sign_in_path_for(resource)
    '/home/index'
  end
  def after_sign_out_path_for(scope)
    '/users/sign_in'
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  after_action :save_my_previous_url, only: [:new, :edit]

  def save_my_previous_url
    session[:previous_url] = URI(request.referrer || '').path
  end

  def index
    @categories = current_user.categories.all
  end
  def show
    @category = Category.all.find(params[:id])
  end
  def new
    @category = current_user.categories.build
  end
  def create
    @category = current_user.categories.build(category_params)
      if @category.save
        redirect_to categories_path, notice: "Category successfully created"
      else
        render :new
      end
  end

  def edit
    @category = Category.all.find(params[:id])
  end
  def update
    @category = Category.all.find(params[:id])

    if @category.update(category_params)
      redirect_to session[:previous_url], notice: "Category updated"
    else
      render :edit
    end
  end
  def destroy
    @category = Category.all.find(params[:id])
    @category.destroy

    redirect_to categories_path, notice: "Category deleted"
  end

  private
  def category_params
    params.require(:category).permit(:name, :description, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    '/home/index'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  after_action :save_my_previous_url, only: [:new, :edit]

  def save_my_previous_url
    session[:previous_url] = URI(request.referrer || '').path
  end

  def index
    @tasks = current_user.tasks.where(:completed => false).order("due_date ASC")
  end
  def show
    @task = Task.all.find(params[:id])
  end
  def new
    @task = current_user.tasks.build
  end
  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to tasks_path, notice: "Task successfully created"
    else
      render :new
    end
  end

  def edit
    @task = Task.all.find(params[:id])
  end
  def update
    @task = Task.all.find(params[:id])
    if @task.update(task_params)
      redirect_to session[:previous_url], notice: "Task updated"
    else
      render :edit
    end
  end
  def destroy
    @task = Task.all.find(params[:id])
    @task.destroy
    redirect_to session[:previous_url], notice: "Task deleted"
  end

  def complete
    @task = Task.all.find(params[:task_id])
    if @task.completed?
      @task.update_attribute(:completion_date, "")
      @task.update_attribute(:completed, false)
      redirect_to request.referrer, notice: "Task marked as incomplete"
    else
      @task.update_attribute(:completion_date, Time.now)
      @task.update_attribute(:completed, true)
      redirect_to request.referrer, notice: "Task marked as complete"
    end
  end

  def today
    @today = current_user.tasks.where("due_date <= ? AND completed = ?", Date.current, false).order("due_date ASC")
  end

  def completed_tasks
    @completed = current_user.tasks.where(:completed => true).order("due_date ASC")
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :category_id, :due_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_category_buttons.html.erb
<%= link_to edit_category_path(category), class: "edit-link" do %>
    <i class="las la-pen"></i>
<% end %>
<%= link_to category_path(category), method: :delete, class: "delete-link", data: { confirm: "Delete #{category.name}?" } do %>
    <i class="las la-trash-alt la-1x"></i>
<% end %>

app/views/categories/_form.html.erb
<%= form_with model: @category do |f| %>
    <div class="form-proper">
        <div>
        <%= f.object.errors.full_messages.join(", ") if f.object.errors.any? %>
        </div>
        <div>
            <%= f.label :name %><br>
            <%= f.text_field :name, class: "text-field" %><br><br>
        </div>
        <div>
            <%= f.label :description %><br>
            <%= f.text_field :description, class: "text-field" %><br><br>
        </div>
        <div>
            <%= f.submit %>
        </div>
    </div>
<% end %>

app/views/categories/edit.html.erb
<%= render "form" %>

app/views/categories/index.html.erb
<div id="category-area">
    <% @categories.each do |category| %>
        <div class="category-item">
            <div class="category-info">
                <%= link_to category.name, category_path(category) %>
            </div>
            <div class="category-buttons">
                <%= render partial: 'category_buttons', locals: {category: category} %>
            </div>
        </div>
    <% end %>
</div>

app/views/categories/new.html.erb
<%= render "form" %>

app/views/categories/show.html.erb
<div id="category-area">
    <div>Name<br><%= @category.name %></div><br>
    <div>Description<br>
        <% if @category.description.blank? %>
            <em>No description</em><br>
        <% else %>
            <%= @category.description %><br>
        <% end %>
    </div><br>
    <div class="category-buttons">
        <%= link_to :back do %>
            <i class="las la-arrow-circle-left"></i>
        <% end %>
        <%= render partial: 'category_buttons', locals: {category: @category} %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple-ToDo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash.any? %>
      <div id="flash-messages">
        <%= notice %>
      </div>
    <% end %>
    <div id="dashboard">
      <div id="user-menu">
        <div id="user-info">
          <i class="lar la-user-circle"></i> <%= current_user.first_name %>
        </div>
        <button><i class="las la-sign-out-alt la-sm"></i><%= link_to('Logout', destroy_user_session_path, method: :delete) %></button>
      </div>
      <div id="menu-tabs">
        <div id="index-buttons">
          <div><%= link_to 'Today', today_path %></div>
          <div><%= link_to 'Tasks', tasks_path %></div>
          <div><%= link_to 'Categories', categories_path %></div>
          <div><%= link_to 'Completed', completed_tasks_path %></div>
        </div>
        <div id="create-buttons">
          <div><%= link_to 'New Task', new_task_path(current_user) %></div>
          <div><%= link_to 'New Category', new_category_path(current_user) %></div>
        </div>
      </div>
  
      <div id="main-area">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple-ToDo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'devise', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= devise_error_messages! %>
    <% flash.each do |key, value| %>
       <div class="flash-messages <%= key %>"><%= value %></div>
    <% end %>
    <div class="main-menu">
    <h1>Simple-ToDo</h1>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: @task do |f| %>
    <div class="form-proper">
        <div>
        <%= f.object.errors.full_messages.join(", ") if f.object.errors.any? %>
        </div>
        <div>
            <%= f.label :category_id %><br>
            <%= f.select :category_id, current_user.categories.collect { |category| [category.name, category.id] } %><br><br>
        </div>
        <div>
            <%= f.label :name %><br>
            <%= f.text_field :name, class: "text-field" %><br><br>
        </div>
        <div>
            <%= f.label :description %><br>
            <%= f.text_field :description, class: "text-field" %><br><br>
        </div>
        <div>
            <%= f.label :due_date %><br>
            <%= f.date_field :due_date %><br><br>
        </div>
        <div>
            <%= f.submit %>
        </div>
    </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="task-item">
    <div class="task-info">
        <div><%= link_to task.name, task_path(task) %> </div>
        <div class="category-name"><%= task.category.name.truncate(27) %></div>
        <div><%= task.due_date.strftime("%B %-d") %></div>
    </div>
    <div class="task-buttons">
        <%= render partial: 'task_buttons', locals: {task: task} %>
    </div>
</div>

app/views/tasks/_task_buttons.html.erb
<%= link_to task_complete_path(task), method: :patch do %>
    <i class="las la-check-circle"></i>
<% end %>
<%= link_to edit_task_path(task) do %>
    <i class="las la-pen"></i>
<% end %>
<%= link_to task_path(task), method: :delete, data: { confirm: "Delete #{task.name}?" } do %>
    <i class="las la-trash-alt la-1x"></i>
<% end %>

app/views/tasks/completed_tasks.html.erb
<div id="task-area">
    <%= render partial: 'task', collection: @completed %>
</div>

app/views/tasks/edit.html.erb
<%= render "form" %>

app/views/tasks/index.html.erb
<div id="task-area">
    <%= render partial: 'task', collection: @tasks %>
</div>

app/views/tasks/new.html.erb
<% if current_user.categories.empty? %>
    <%= "Please make a category first before creating a task" %>
<% else %>
    <%= render "form" %>
<% end %>

app/views/tasks/show.html.erb
<div id="task-area">
    <div>Name<br><%= @task.name %></div><br>
    <div>Description<br>
        <% if @task.description.blank? %>
            <em>No description</em><br>
        <% else %>
            <%= @task.description %><br>
        <% end %>
    </div><br>
    <div>Due date<br><%= @task.due_date.strftime("%B %-d") %></div><br>
    <% if @task.completed? %>
        <div>Completed at<br> <%= @task.completion_date.localtime.strftime('%B %e at %l:%M %p') %></div>
    <% else %>
        <div>Not yet complete</div>
    <% end %>
    <br>
    <div class="show-task-buttons">
        <%= link_to :back do %>
            <i class="las la-arrow-circle-left"></i>
        <% end %>
        <%= render partial: 'task_buttons', locals: {task: @task} %>
    </div>
</div>

app/views/tasks/today.html.erb
<div id="task-area">
    <%= render partial: 'task', collection: @today %>
</div>